In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time
import datetime
from dateutil import parser
from datetime import datetime

In [26]:
incidents = pd.read_csv('data/cleaned_data_no_zeros.csv', sep = None, dtype={'YEAR OCCURRED': np.int_, 'MONTH OCCURRED': np.int_,'GEO CODE': np.str_, 'CRIME CATEGORY DESCRIPTION': np.str_,}, engine = 'python')

## Parsing Discrete Category Data to Create OneHot Encodings
### Parse Crime Data & GeoCodes:
* Create Columns for Encodings
* Find Unique Values
* Encode Using np.eye()
* Map Unique Values to Corresponding Encodings
* Iterate through DataFrame to Add Encoded Values to Corresponding Spots
* Add Columns to Data Frames

In [27]:
length = len(incidents)

# Create columns for onehot_encodings
onehot_crime_array =  [[]] * length
onehot_geocode_array =  [[]] * length

# Find Unique Values
unique_crime_categories = incidents['CRIME CATEGORY DESCRIPTION'].unique()
unique_geocode = incidents['GEO CODE'].unique()

# Encode Using np.eye()
unique_crimes_encoding = np.eye(len(unique_crime_categories))
unique_geocode_encoding = np.eye(len(unique_geocode))


# Map Unique Values to Corresponding Encodings 

crime_dict = {}
for i in range(len(unique_crime_categories)):
    crime_dict[unique_crime_categories[i]] = unique_crimes_encoding[i]

geocode_dict = {}
for i in range(len(unique_geocode)):
    geocode_dict[unique_geocode[i]] = unique_geocode_encoding[i]
    
# Iterate through Data Frame to Add Encoded Values to Corresponding Spots

for i in range(length):
    onehot_crime_array[i] = crime_dict[incidents['CRIME CATEGORY DESCRIPTION'][i]]
    
for i in range(length):
    onehot_geocode_array[i] = geocode_dict[incidents['GEO CODE'][i]] 

# Add Columns to Data Frames

incidents['CRIME CATEGORY ARRAY'] = onehot_crime_array
incidents['GEO CODE ARRAY'] = onehot_geocode_array

# Get Results:

incidents.head()

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


Unnamed: 0 CRIME CATEGORY DESCRIPTION  RESPONSE TIME  MINS OF DAY  \
0           1           Traffic Offenses           14.0       1138.0   
1           2                   Accident            7.0        945.0   
2           7         Disorderly Conduct            9.0        665.0   
3           9           Traffic Offenses            6.0       1176.0   
4          11        Crisis Intervention            6.0       1044.0   

   DAY OF WEEK  DAY OF MONTH  DAY OF YEAR  MONTH OCCURRED  YEAR OCCURRED  \
0          1.0          18.0        169.0               6           2019   
1          4.0          28.0        241.0               8           2020   
2          4.0           8.0        312.0              11           2013   
3          0.0          23.0        328.0              11           2020   
4          6.0          22.0        327.0              11           2020   

  GEO CODE   LATITUDE  LONGITUDE  \
0   546-15        NaN        NaN   
1   546-11  40.116511 -88.210833   
2   576-11  40.101881 -88.200156   
3   605-08        NaN        NaN   
4   577-04        NaN        NaN   

                                CRIME CATEGORY ARRAY  \
0  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                      GEO CODE ARRAY  
0  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...